### ISSUE TITLE
Treeview conflict

### ISSUE THREAD

**Issue by herrDOS** [pupunzi/jquery.mb.miniAudioPlayer#8]
After adding this player Treeview plugin (https://github.com/jzaefferer/jquery-treeview/blob/master/jquery.treeview.js) stops working. Firebug shows unknown error in jQuery. 

Example: http://www.mosreklama.net/btl/organizacija-treningov
Try to push any plus icon in the left menu. When treeview plugin works the plus elements has toggler() function for onclick. Example: http://eng.mosreklama.net/internet

**Comment by pupunzi** [comment]
Hi,
you are including a really old jQuery version (1.7.2)... I don't know if that could be the problem as the error thrown is too generic and fired from the minified version. You could first try to include at least jQuery 1.9.x (better if the latest release) not minified to see where the error is.

Bye,
Matteo

**Comment by herrDOS** [comment]
Hi Matteo!

I did as you recommended. 
Conflict between plugins, of course, is still here. I want to mention that when I'm including just jquery.jplayer.min.js treeview plugin works correctly. The problem appears only if I'm including jquery.mb.miniPlayer.js
I've really tried various of combinations but couldn't find the decision myself.
